---

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create packer_binary_cache_dir
  file:
    path: "{{ packer_binary_cache_dir }}"
    mode: 0755
    owner: "{{ packer_binary_owner }}"
    group: "{{ packer_binary_group }}"
    state: directory

- name: Fetch packer archive
  get_url:
    url: "{{ packer_binary_url }}"
    dest: "{{ packer_binary_cache_dir }}"
    owner: "{{ packer_binary_owner }}"
    group: "{{ packer_binary_group }}"
    sha256sum: "{{ packer_binary_sha256sum[packer_binary_filename] }}"

- name: Create destination directory
  file:
    path: "{{ packer_binary_dir }}/{{ packer_binary_sym_name }}"
    mode: 0755
    owner: "{{ packer_binary_owner }}"
    group: "{{ packer_binary_group }}"
    state: directory

- name: Extract packer archive
  unarchive:
    src: "{{ packer_binary_cache_dir }}/{{ packer_binary_filename }}"
    owner: "{{ packer_binary_owner }}"
    group: "{{ packer_binary_group }}"
    dest:    "{{ packer_binary_dir }}/{{ packer_binary_sym_name }}"
    creates: "{{ packer_binary_dir }}/{{ packer_binary_sym_name }}/packer"
    mode: "{{ packer_binary_mode }}"
    remote_src: yes
  when: "ansible_version.full | version_compare('2.2.0.0', '>=')"

- name: Extract packer archive
  # XXX for backward compatibility
  command: "unzip {{ packer_binary_cache_dir + '/' + packer_binary_filename | quote }}"
  args:
    creates: "{{ packer_binary_dir }}/{{ packer_binary_sym_name }}/packer"
    chdir: "{{ packer_binary_dir }}/{{ packer_binary_sym_name }}"
  when: "ansible_version.full | version_compare('2.2.0.0', '<')"

- name: Set file mode on packer_binary_dir/packer_binary_sym_name and all files under it
  # XXX for backward compatibility
  file:
    path: "{{ packer_binary_dir }}/{{ packer_binary_sym_name }}"
    owner: "{{ packer_binary_owner }}"
    group: "{{ packer_binary_group }}"
    mode: "{{ packer_binary_mode }}"
    recurse: yes
    state: directory
  when: "ansible_version.full | version_compare('2.2.0.0', '<')"

- name: Create symlink to the binary
  file:
    path: "{{ packer_binary_path }}"
    src: "{{ packer_binary_dir }}/{{ packer_binary_sym_name }}/packer"
    state: link
